# Generated by Django 4.1 on 2022-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Фото'),
        ),
    ]
