# Generated by Django 4.1 on 2022-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(upload_to='img/', verbose_name='Фото'),
        ),
    ]
